.TH "src/device.c" 3 "Mon May 14 2018" "Version 0.0.1b" "Fiber(KernelModule)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/device.c \- This file contains the implementation of the char device\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'device\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBinit_device\fP (void)"
.br
.RI "Init the device inspired by https://www.linuxjournal.com/article/2920\&. "
.ti -1c
.RI "void \fBdestroy_device\fP (void)"
.br
.RI "Destroy the device\&. "
.in -1c
.SH "Detailed Description"
.PP 
This file contains the implementation of the char device\&. 


.PP
\fBAuthor:\fP
.RS 4
Gabriele Proietti Mattia gabry.gabry@hotmail.it 
.PP
Alexandru Daniel Tufa alex.tufa94@gmail.com 
.RE
.PP
\fBDate:\fP
.RS 4
2018-05-06 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "int init_device (void)"

.PP
Init the device inspired by https://www.linuxjournal.com/article/2920\&. 
.PP
\fBReturns:\fP
.RS 4
int 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Fiber(KernelModule) from the source code\&.
