.TH "fiber_dev" 3 "Mon May 14 2018" "Version 0.0.1b" "Fiber(KernelModule)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fiber_dev \- The main structure of the fiber char device\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <device\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct miscdevice \fBdevice\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The main structure of the fiber char device\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Fiber(KernelModule) from the source code\&.
