.TH "include/fiber.h" 3 "Mon May 14 2018" "Version 0.0.1b" "Fiber(KernelModule)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/fiber.h \- This file contains definitions and macros of the starting point part of the module\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'common\&.h'\fP
.br
\fC#include 'device\&.h'\fP
.br
\fC#include 'proc\&.h'\fP
.br
\fC#include <linux/init\&.h>\fP
.br
\fC#include <linux/module\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBFIBER_LOG\fP   ': FIBER: '"
.br
.in -1c
.SH "Detailed Description"
.PP 
This file contains definitions and macros of the starting point part of the module\&. 


.PP
\fBAuthor:\fP
.RS 4
Gabriele Proietti Mattia gabry.gabry@hotmail.it 
.PP
Alexandru Daniel Tufa alex.tufa94@gmail.com 
.RE
.PP
\fBDate:\fP
.RS 4
2018-05-13 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Fiber(KernelModule) from the source code\&.
