.TH "fibers_list" 3 "Mon May 14 2018" "Version 0.0.1b" "Fiber(KernelModule)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fibers_list \- A generic list of fibers\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <core\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBfiber_node_t\fP * \fBhead\fP"
.br
.ti -1c
.RI "\fBfiber_node_t\fP * \fBtail\fP"
.br
.ti -1c
.RI "unsigned \fBfibers_count\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A generic list of fibers\&. 

The list has the purpose of containing the list of fibers for a given process\&. The list can be considered empty when at least one of \fBfibers_list::head\fP or \fBfibers_list::tail\fP is pointing to \fCNULL\fP\&. 
.SH "Member Data Documentation"
.PP 
.SS "unsigned fibers_list::fibers_count"
Number of fibers created 
.SS "\fBfiber_node_t\fP* fibers_list::head"
The first element in the list 
.SS "\fBfiber_node_t\fP* fibers_list::tail"
The last element in the list 

.SH "Author"
.PP 
Generated automatically by Doxygen for Fiber(KernelModule) from the source code\&.
