.TH "fiber" 3 "Mon May 14 2018" "Version 0.0.1b" "Fiber(KernelModule)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fiber \- A node in the \fBfibers_list\fP\&. This type fully represent a \fCfiber\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <core\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBfiber_node_t\fP * \fBprev\fP"
.br
.ti -1c
.RI "\fBfiber_node_t\fP * \fBnext\fP"
.br
.ti -1c
.RI "unsigned \fBid\fP"
.br
.ti -1c
.RI "void * \fBstarting_function\fP"
.br
.ti -1c
.RI "unsigned long \fBbase_user_stack_pointer\fP"
.br
.ti -1c
.RI "\fBfiber_state_t\fP \fBstate\fP"
.br
.ti -1c
.RI "struct pt_regs \fBregs\fP"
.br
.ti -1c
.RI "pid_t \fBcreated_by\fP"
.br
.ti -1c
.RI "unsigned \fBsuccess_activations_count\fP"
.br
.ti -1c
.RI "unsigned \fBfailed_activations_count\fP"
.br
.ti -1c
.RI "unsigned long \fBtotal_time\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A node in the \fBfibers_list\fP\&. This type fully represent a \fCfiber\fP\&. 

This is the complete description of a fiber\&. 
.SH "Member Data Documentation"
.PP 
.SS "unsigned fiber::id"
Unique if of the fiber, used for 
.SS "\fBfiber_node_t\fP* fiber::next"
Pointer to the next element in the list 
.SS "\fBfiber_node_t\fP* fiber::prev"
Pointer to the previous element in the list 

.SH "Author"
.PP 
Generated automatically by Doxygen for Fiber(KernelModule) from the source code\&.
