.TH "include/ioctlcmd.h" 3 "Mon May 14 2018" "Version 0.0.1b" "Fiber(KernelModule)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/ioctlcmd.h \- This file contains definitions of ioctl commands\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <linux/ioctl\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBFIBER_IOC_MAGIC\fP   0xF1"
.br
.ti -1c
.RI "#define \fBFIBER_IOCRESET\fP   _IO(FIBER_IOC_MAGIC, 0)"
.br
.ti -1c
.RI "#define \fBFIBER_IOC_CONVERTTHREADTOFIBER\fP   _IO(FIBER_IOC_MAGIC, 1)"
.br
.ti -1c
.RI "#define \fBFIBER_IOC_CREATEFIBER\fP   _IOW(FIBER_IOC_MAGIC, 2, int)"
.br
.ti -1c
.RI "#define \fBFIBER_IOC_SWITCHTOFIBER\fP   _IO(FIBER_IOC_MAGIC, 3)"
.br
.ti -1c
.RI "#define \fBFIBER_IOC_FLS_ALLOC\fP   _IOWR(FIBER_IOC_MAGIC, 4, int)"
.br
.ti -1c
.RI "#define \fBFIBER_IOC_FLS_FREE\fP   _IOW(FIBER_IOC_MAGIC, 5, int)"
.br
.ti -1c
.RI "#define \fBFIBER_IOC_FLS_GET\fP   _IOR(FIBER_IOC_MAGIC, 6, int)"
.br
.ti -1c
.RI "#define \fBFIBER_IOC_FLS_SET\fP   _IOW(FIBER_IOC_MAGIC, 7, int)"
.br
.ti -1c
.RI "#define \fBFIBER_IOC_MAXNR\fP   7"
.br
.in -1c
.SH "Detailed Description"
.PP 
This file contains definitions of ioctl commands\&. 


.SH "Module operations"
.PP
.PP
We define the following operations for the module that are mapped with the library (Library -> Module)
.IP "\(bu" 2
ConvertThreadToFiber -> FIBER_IOC_CONVERTTHREADTOFIBER
.IP "\(bu" 2
CreateFiber -> FIBER_IOC_CREATEFIBER
.IP "\(bu" 2
SwitchToFiber -> FIBER_IOC_SWITCHTOFIBER
.IP "\(bu" 2
FlsAlloc -> FLS_ALLOC
.IP "\(bu" 2
FlsFree -> FLS_FREE
.IP "\(bu" 2
FlsGetValue -> FLS_GET
.IP "\(bu" 2
FlsSetValue -> FLS_SET
.PP
.PP
\fBAuthor:\fP
.RS 4
Gabriele Proietti Mattia gabry.gabry@hotmail.it 
.PP
Alexandru Daniel Tufa alex.tufa94@gmail.com 
.RE
.PP
\fBDate:\fP
.RS 4
2018-05-07 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Fiber(KernelModule) from the source code\&.
